### ISSUE TITLE
MS4: Function 4 + Test

### ISSUE THREAD

**Issue by Farhan-Faisal** [UBC-MDS/DSCI522-2425-22-wine-chromatic-profile#58]

**Comment by Farhan-Faisal** [comment]
you already made this function: # Validate column names
def validate_column_names(wine, correct_columns):
    extracted_columns = set(wine.columns)
    if extracted_columns != correct_columns:
        wrong_columns = extracted_columns.difference(correct_columns)
        missing_columns = correct_columns.difference(extracted_columns)
        if wrong_columns and missing_columns:
            raise ValueError(f"Unexpected columns: {list(wrong_columns)}, missing columns: {list(missing_columns)}")
        elif wrong_columns:
            raise ValueError(f"Unexpected columns: {list(wrong_columns)}")
        elif missing_columns:
            raise ValueError(f"Missing columns: {list(missing_columns)}")
    else:
        print("Column name test passed!") 

maybe just test it?

**Comment by gracez-20** [comment]
Good idea! I'm on it

> you already made this function:
> 
> ```
> # Validate column names
> def validate_column_names(wine, correct_columns):  
>     extracted_columns = set(wine.columns)
>     if extracted_columns != correct_columns:  
>         wrong_columns = extracted_columns.difference(correct_columns)
>         missing_columns = correct_columns.difference(extracted_columns)
>         if wrong_columns and missing_columns:  
>             raise ValueError(f"Unexpected columns: {list(wrong_columns)}, missing columns: {list(missing_columns)}")
>         elif wrong_columns:  
>             raise ValueError(f"Unexpected columns: {list(wrong_columns)}")
>         elif missing_columns:
>             raise ValueError(f"Missing columns: {list(missing_colu. mns)}")
>     else:
>         print("Column name test passed!") 
> ```
> 
> maybe just test it?
